# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a20222359c7fae7500ef4d16c9bd82325178c918c786f2ca2c0a2b612aa96412bc150968a143ddb9dc9e68beffcfd6c5c7eb1b1bdea98f0265437b45373be0d0

test:
  secret_key_base: 11c7389286eb7dbf23086a2709dea556e0a4709c7a3769f40d3a50e9a3e821f82940ca3ecbd561a1b2e3e2789bc9355e48908fa80f95024ea263cae542b49761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
